apiVersion: v1
kind: Service
metadata:
  name: solar-system-svc
  labels:
    app: solar-system
spec:
  selector:
    app: solar-system
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort
